"""Constants for Climate Relay."""

DOMAIN = "climate_relay_core"
DEFAULT_NAME = "Climate Relay"

CONF_FALLBACK_TEMPERATURE = "fallback_temperature"
CONF_ROOMS = "rooms"
CONF_ROOM_NAME = "name"
CONF_PRIMARY_CLIMATE_ENTITY_ID = "primary_climate_entity_id"
CONF_HUMIDITY_ENTITY_ID = "humidity_entity_id"
CONF_WINDOW_ENTITY_ID = "window_entity_id"
CONF_HOME_TARGET_TEMPERATURE = "home_target_temperature"
CONF_AWAY_TARGET_TYPE = "away_target_type"
CONF_AWAY_TARGET_TEMPERATURE = "away_target_temperature"
CONF_SCHEDULE = "schedule"
CONF_SCHEDULE_HOME_START = "schedule_home_start"
CONF_SCHEDULE_HOME_END = "schedule_home_end"
CONF_MANUAL_OVERRIDE_RESET_ENABLED = "manual_override_reset_enabled"
CONF_MANUAL_OVERRIDE_RESET_TIME = "manual_override_reset_time"
CONF_PERSON_ENTITY_IDS = "person_entity_ids"
CONF_SIMULATION_MODE = "simulation_mode"
CONF_UNKNOWN_STATE_HANDLING = "unknown_state_handling"
CONF_VERBOSE_LOGGING = "verbose_logging"

ATTR_ACTIVE_CONTROL_CONTEXT = "active_control_context"
ATTR_DEGRADATION_STATUS = "degradation_status"
ATTR_EFFECTIVE_PRESENCE = "effective_presence"
ATTR_FALLBACK_TEMPERATURE = "fallback_temperature"
ATTR_HUMIDITY_ENTITY_ID = "humidity_entity_id"
ATTR_MANUAL_OVERRIDE_RESET_TIME = "manual_override_reset_time"
ATTR_NEXT_CHANGE_AT = "next_change_at"
ATTR_PRIMARY_CLIMATE_ENTITY_ID = "primary_climate_entity_id"
ATTR_SIMULATION_MODE = "simulation_mode"
ATTR_UNKNOWN_STATE_HANDLING = "unknown_state_handling"
ATTR_WINDOW_ENTITY_ID = "window_entity_id"

DEFAULT_AWAY_TARGET_TYPE = "absolute"
DEFAULT_FALLBACK_TEMPERATURE = 20.0
DEFAULT_SCHEDULE_HOME_END = "22:00:00"
DEFAULT_SCHEDULE_HOME_START = "06:00:00"
DEFAULT_UNKNOWN_STATE_HANDLING = "away"

SERVICE_SET_GLOBAL_MODE = "set_global_mode"
ENTITY_TRANSLATION_KEY_PRESENCE_CONTROL = "presence_control"
