"""Constants for Climate Relay."""

DOMAIN = "climate_relay_core"
DEFAULT_NAME = "Climate Relay"

CONF_FALLBACK_TEMPERATURE = "fallback_temperature"
CONF_ROOMS = "rooms"
CONF_ROOM_NAME = "name"
CONF_PRIMARY_CLIMATE_ENTITY_ID = "primary_climate_entity_id"
CONF_HUMIDITY_ENTITY_ID = "humidity_entity_id"
CONF_WINDOW_ENTITY_ID = "window_entity_id"
CONF_WINDOW_ACTION_TYPE = "window_action_type"
CONF_WINDOW_CUSTOM_TEMPERATURE = "window_custom_temperature"
CONF_WINDOW_OPEN_DELAY_SECONDS = "window_open_delay_seconds"
CONF_HOME_TARGET_TEMPERATURE = "home_target_temperature"
CONF_AWAY_TARGET_TYPE = "away_target_type"
CONF_AWAY_TARGET_TEMPERATURE = "away_target_temperature"
CONF_SCHEDULE = "schedule"
CONF_SCHEDULE_HOME_START = "schedule_home_start"
CONF_SCHEDULE_HOME_END = "schedule_home_end"
CONF_MANUAL_OVERRIDE_RESET_ENABLED = "manual_override_reset_enabled"
CONF_MANUAL_OVERRIDE_RESET_TIME = "manual_override_reset_time"
CONF_PERSON_ENTITY_IDS = "person_entity_ids"
CONF_SIMULATION_MODE = "simulation_mode"
CONF_UNKNOWN_STATE_HANDLING = "unknown_state_handling"
CONF_VERBOSE_LOGGING = "verbose_logging"

ATTR_ACTIVE_CONTROL_CONTEXT = "active_control_context"
ATTR_CAN_CLEAR_OVERRIDE = "can_clear_override"
ATTR_CAN_SET_OVERRIDE = "can_set_override"
ATTR_DEGRADATION_STATUS = "degradation_status"
ATTR_EFFECTIVE_PRESENCE = "effective_presence"
ATTR_FALLBACK_TEMPERATURE = "fallback_temperature"
ATTR_HUMIDITY_ENTITY_ID = "humidity_entity_id"
ATTR_MANUAL_OVERRIDE_ACTIVE = "manual_override_active"
ATTR_MANUAL_OVERRIDE_ENDS_AT = "manual_override_ends_at"
ATTR_MANUAL_OVERRIDE_TARGET_TEMPERATURE = "manual_override_target_temperature"
ATTR_MANUAL_OVERRIDE_TERMINATION_TYPE = "manual_override_termination_type"
ATTR_MANUAL_OVERRIDE_RESET_TIME = "manual_override_reset_time"
ATTR_NEXT_CHANGE_AT = "next_change_at"
ATTR_OVERRIDE_ENDS_AT = "override_ends_at"
ATTR_PRIMARY_CLIMATE_ENTITY_ID = "primary_climate_entity_id"
ATTR_SCHEDULE_HOME_END = "schedule_home_end"
ATTR_SCHEDULE_HOME_START = "schedule_home_start"
ATTR_SIMULATION_MODE = "simulation_mode"
ATTR_SUPPORTED_ROOM_ACTIONS = "supported_room_actions"
ATTR_UNKNOWN_STATE_HANDLING = "unknown_state_handling"
ATTR_WINDOW_ENTITY_ID = "window_entity_id"

DEFAULT_AWAY_TARGET_TYPE = "absolute"
DEFAULT_FALLBACK_TEMPERATURE = 20.0
DEFAULT_SCHEDULE_HOME_END = "22:00:00"
DEFAULT_SCHEDULE_HOME_START = "06:00:00"
DEFAULT_UNKNOWN_STATE_HANDLING = "away"
DEFAULT_WINDOW_ACTION_TYPE = "minimum_temperature"
DEFAULT_WINDOW_CUSTOM_TEMPERATURE = 12.0
DEFAULT_WINDOW_OPEN_DELAY_SECONDS = 300

SERVICE_SET_GLOBAL_MODE = "set_global_mode"
SERVICE_SET_AREA_OVERRIDE = "set_area_override"
SERVICE_CLEAR_AREA_OVERRIDE = "clear_area_override"
ENTITY_TRANSLATION_KEY_PRESENCE_CONTROL = "presence_control"
